name: build_guide

# execute this workflow automatically when a we push to master
on:
  workflow_dispatch:

jobs:

  build_docs_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme

      - name: make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/_build/html
